version: "2"
linters:
  settings:
    dupl:
      threshold: 150
    goconst:
      min-len: 2
      min-occurrences: 2
    lll:
      line-length: 140
    misspell:
      locale: US
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/reportportal/goRP/v5)
    goimports:
      local-prefixes:
        - github.com/reportportal/goRP/v5
    gofumpt:
      module-path: github.com/reportportal/goRP/v5
      extra-rules: true