version: "2"
linters:
  settings:
    dupl:
      threshold: 150
    goconst:
      min-len: 2
      min-occurrences: 2
    lll:
      line-length: 140
    misspell:
      locale: US
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/reportportal/goRP/v5
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
