/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalApiModelInstanceUserStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalApiModelInstanceUserStats{}

// ComEpamReportportalApiModelInstanceUserStats struct for ComEpamReportportalApiModelInstanceUserStats
type ComEpamReportportalApiModelInstanceUserStats struct {
	OrgStats *ComEpamReportportalApiModelInstanceUserStatsOrgStats `json:"org_stats,omitempty"`
}

// NewComEpamReportportalApiModelInstanceUserStats instantiates a new ComEpamReportportalApiModelInstanceUserStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalApiModelInstanceUserStats() *ComEpamReportportalApiModelInstanceUserStats {
	this := ComEpamReportportalApiModelInstanceUserStats{}
	return &this
}

// NewComEpamReportportalApiModelInstanceUserStatsWithDefaults instantiates a new ComEpamReportportalApiModelInstanceUserStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalApiModelInstanceUserStatsWithDefaults() *ComEpamReportportalApiModelInstanceUserStats {
	this := ComEpamReportportalApiModelInstanceUserStats{}
	return &this
}

// GetOrgStats returns the OrgStats field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelInstanceUserStats) GetOrgStats() ComEpamReportportalApiModelInstanceUserStatsOrgStats {
	if o == nil || IsNil(o.OrgStats) {
		var ret ComEpamReportportalApiModelInstanceUserStatsOrgStats
		return ret
	}
	return *o.OrgStats
}

// GetOrgStatsOk returns a tuple with the OrgStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelInstanceUserStats) GetOrgStatsOk() (*ComEpamReportportalApiModelInstanceUserStatsOrgStats, bool) {
	if o == nil || IsNil(o.OrgStats) {
		return nil, false
	}
	return o.OrgStats, true
}

// HasOrgStats returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelInstanceUserStats) HasOrgStats() bool {
	if o != nil && !IsNil(o.OrgStats) {
		return true
	}

	return false
}

// SetOrgStats gets a reference to the given ComEpamReportportalApiModelInstanceUserStatsOrgStats and assigns it to the OrgStats field.
func (o *ComEpamReportportalApiModelInstanceUserStats) SetOrgStats(v ComEpamReportportalApiModelInstanceUserStatsOrgStats) {
	o.OrgStats = &v
}

func (o ComEpamReportportalApiModelInstanceUserStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalApiModelInstanceUserStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrgStats) {
		toSerialize["org_stats"] = o.OrgStats
	}
	return toSerialize, nil
}

type NullableComEpamReportportalApiModelInstanceUserStats struct {
	value *ComEpamReportportalApiModelInstanceUserStats
	isSet bool
}

func (v NullableComEpamReportportalApiModelInstanceUserStats) Get() *ComEpamReportportalApiModelInstanceUserStats {
	return v.value
}

func (v *NullableComEpamReportportalApiModelInstanceUserStats) Set(val *ComEpamReportportalApiModelInstanceUserStats) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalApiModelInstanceUserStats) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalApiModelInstanceUserStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalApiModelInstanceUserStats(val *ComEpamReportportalApiModelInstanceUserStats) *NullableComEpamReportportalApiModelInstanceUserStats {
	return &NullableComEpamReportportalApiModelInstanceUserStats{value: val, isSet: true}
}

func (v NullableComEpamReportportalApiModelInstanceUserStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalApiModelInstanceUserStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
