/*
ReportPortal

ReportPortal API documentation

API version: develop-553
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ{}

// ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ struct for ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ
type ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ struct {
	Id    *string `json:"id,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ instantiates a new ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ() *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ {
	this := ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ{}
	return &this
}

// NewComEpamReportportalBaseCoreTmsDtoTmsRequirementRQWithDefaults instantiates a new ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseCoreTmsDtoTmsRequirementRQWithDefaults() *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ {
	this := ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) SetId(v string) {
	o.Id = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) SetValue(v string) {
	o.Value = &v
}

func (o ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ struct {
	value *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ
	isSet bool
}

func (v NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) Get() *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ {
	return v.value
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) Set(val *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ(val *ComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) *NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ {
	return &NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoTmsRequirementRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
