/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ComEpamReportportalBaseModelWidgetWidgetRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelWidgetWidgetRQ{}

// ComEpamReportportalBaseModelWidgetWidgetRQ struct for ComEpamReportportalBaseModelWidgetWidgetRQ
type ComEpamReportportalBaseModelWidgetWidgetRQ struct {
	Description       *string                                              `json:"description,omitempty"`
	Name              string                                               `json:"name"`
	WidgetType        string                                               `json:"widgetType"`
	ContentParameters *ComEpamReportportalBaseModelWidgetContentParameters `json:"contentParameters,omitempty"`
	FilterIds         []int64                                              `json:"filterIds,omitempty"`
}

type _ComEpamReportportalBaseModelWidgetWidgetRQ ComEpamReportportalBaseModelWidgetWidgetRQ

// NewComEpamReportportalBaseModelWidgetWidgetRQ instantiates a new ComEpamReportportalBaseModelWidgetWidgetRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelWidgetWidgetRQ(name string, widgetType string) *ComEpamReportportalBaseModelWidgetWidgetRQ {
	this := ComEpamReportportalBaseModelWidgetWidgetRQ{}
	this.Name = name
	this.WidgetType = widgetType
	return &this
}

// NewComEpamReportportalBaseModelWidgetWidgetRQWithDefaults instantiates a new ComEpamReportportalBaseModelWidgetWidgetRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelWidgetWidgetRQWithDefaults() *ComEpamReportportalBaseModelWidgetWidgetRQ {
	this := ComEpamReportportalBaseModelWidgetWidgetRQ{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) SetName(v string) {
	o.Name = v
}

// GetWidgetType returns the WidgetType field value
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetWidgetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WidgetType
}

// GetWidgetTypeOk returns a tuple with the WidgetType field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetWidgetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WidgetType, true
}

// SetWidgetType sets field value
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) SetWidgetType(v string) {
	o.WidgetType = v
}

// GetContentParameters returns the ContentParameters field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetContentParameters() ComEpamReportportalBaseModelWidgetContentParameters {
	if o == nil || IsNil(o.ContentParameters) {
		var ret ComEpamReportportalBaseModelWidgetContentParameters
		return ret
	}
	return *o.ContentParameters
}

// GetContentParametersOk returns a tuple with the ContentParameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetContentParametersOk() (*ComEpamReportportalBaseModelWidgetContentParameters, bool) {
	if o == nil || IsNil(o.ContentParameters) {
		return nil, false
	}
	return o.ContentParameters, true
}

// HasContentParameters returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) HasContentParameters() bool {
	if o != nil && !IsNil(o.ContentParameters) {
		return true
	}

	return false
}

// SetContentParameters gets a reference to the given ComEpamReportportalBaseModelWidgetContentParameters and assigns it to the ContentParameters field.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) SetContentParameters(v ComEpamReportportalBaseModelWidgetContentParameters) {
	o.ContentParameters = &v
}

// GetFilterIds returns the FilterIds field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetFilterIds() []int64 {
	if o == nil || IsNil(o.FilterIds) {
		var ret []int64
		return ret
	}
	return o.FilterIds
}

// GetFilterIdsOk returns a tuple with the FilterIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) GetFilterIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.FilterIds) {
		return nil, false
	}
	return o.FilterIds, true
}

// HasFilterIds returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) HasFilterIds() bool {
	if o != nil && !IsNil(o.FilterIds) {
		return true
	}

	return false
}

// SetFilterIds gets a reference to the given []int64 and assigns it to the FilterIds field.
func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) SetFilterIds(v []int64) {
	o.FilterIds = v
}

func (o ComEpamReportportalBaseModelWidgetWidgetRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelWidgetWidgetRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	toSerialize["widgetType"] = o.WidgetType
	if !IsNil(o.ContentParameters) {
		toSerialize["contentParameters"] = o.ContentParameters
	}
	if !IsNil(o.FilterIds) {
		toSerialize["filterIds"] = o.FilterIds
	}
	return toSerialize, nil
}

func (o *ComEpamReportportalBaseModelWidgetWidgetRQ) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"widgetType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComEpamReportportalBaseModelWidgetWidgetRQ := _ComEpamReportportalBaseModelWidgetWidgetRQ{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComEpamReportportalBaseModelWidgetWidgetRQ)

	if err != nil {
		return err
	}

	*o = ComEpamReportportalBaseModelWidgetWidgetRQ(varComEpamReportportalBaseModelWidgetWidgetRQ)

	return err
}

type NullableComEpamReportportalBaseModelWidgetWidgetRQ struct {
	value *ComEpamReportportalBaseModelWidgetWidgetRQ
	isSet bool
}

func (v NullableComEpamReportportalBaseModelWidgetWidgetRQ) Get() *ComEpamReportportalBaseModelWidgetWidgetRQ {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelWidgetWidgetRQ) Set(val *ComEpamReportportalBaseModelWidgetWidgetRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelWidgetWidgetRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelWidgetWidgetRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelWidgetWidgetRQ(val *ComEpamReportportalBaseModelWidgetWidgetRQ) *NullableComEpamReportportalBaseModelWidgetWidgetRQ {
	return &NullableComEpamReportportalBaseModelWidgetWidgetRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelWidgetWidgetRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelWidgetWidgetRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
