/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseCoreTmsDtoProductVersionRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseCoreTmsDtoProductVersionRQ{}

// ComEpamReportportalBaseCoreTmsDtoProductVersionRQ struct for ComEpamReportportalBaseCoreTmsDtoProductVersionRQ
type ComEpamReportportalBaseCoreTmsDtoProductVersionRQ struct {
	Id            *int64  `json:"id,omitempty"`
	Version       *string `json:"version,omitempty"`
	Documentation *string `json:"documentation,omitempty"`
	ProjectId     *int64  `json:"projectId,omitempty"`
}

// NewComEpamReportportalBaseCoreTmsDtoProductVersionRQ instantiates a new ComEpamReportportalBaseCoreTmsDtoProductVersionRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseCoreTmsDtoProductVersionRQ() *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ {
	this := ComEpamReportportalBaseCoreTmsDtoProductVersionRQ{}
	return &this
}

// NewComEpamReportportalBaseCoreTmsDtoProductVersionRQWithDefaults instantiates a new ComEpamReportportalBaseCoreTmsDtoProductVersionRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseCoreTmsDtoProductVersionRQWithDefaults() *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ {
	this := ComEpamReportportalBaseCoreTmsDtoProductVersionRQ{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) SetId(v int64) {
	o.Id = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) SetVersion(v string) {
	o.Version = &v
}

// GetDocumentation returns the Documentation field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetDocumentation() string {
	if o == nil || IsNil(o.Documentation) {
		var ret string
		return ret
	}
	return *o.Documentation
}

// GetDocumentationOk returns a tuple with the Documentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetDocumentationOk() (*string, bool) {
	if o == nil || IsNil(o.Documentation) {
		return nil, false
	}
	return o.Documentation, true
}

// HasDocumentation returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) HasDocumentation() bool {
	if o != nil && !IsNil(o.Documentation) {
		return true
	}

	return false
}

// SetDocumentation gets a reference to the given string and assigns it to the Documentation field.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) SetDocumentation(v string) {
	o.Documentation = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetProjectId() int64 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int64
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) GetProjectIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int64 and assigns it to the ProjectId field.
func (o *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) SetProjectId(v int64) {
	o.ProjectId = &v
}

func (o ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Documentation) {
		toSerialize["documentation"] = o.Documentation
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ struct {
	value *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ
	isSet bool
}

func (v NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ) Get() *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ {
	return v.value
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ) Set(val *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ(val *ComEpamReportportalBaseCoreTmsDtoProductVersionRQ) *NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ {
	return &NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoProductVersionRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
