/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseModelProjectUpdateProjectRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelProjectUpdateProjectRQ{}

// ComEpamReportportalBaseModelProjectUpdateProjectRQ struct for ComEpamReportportalBaseModelProjectUpdateProjectRQ
type ComEpamReportportalBaseModelProjectUpdateProjectRQ struct {
	Users         *map[string]string                                                   `json:"users,omitempty"`
	Configuration *ComEpamReportportalBaseModelProjectConfigProjectConfigurationUpdate `json:"configuration,omitempty"`
}

// NewComEpamReportportalBaseModelProjectUpdateProjectRQ instantiates a new ComEpamReportportalBaseModelProjectUpdateProjectRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelProjectUpdateProjectRQ() *ComEpamReportportalBaseModelProjectUpdateProjectRQ {
	this := ComEpamReportportalBaseModelProjectUpdateProjectRQ{}
	return &this
}

// NewComEpamReportportalBaseModelProjectUpdateProjectRQWithDefaults instantiates a new ComEpamReportportalBaseModelProjectUpdateProjectRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelProjectUpdateProjectRQWithDefaults() *ComEpamReportportalBaseModelProjectUpdateProjectRQ {
	this := ComEpamReportportalBaseModelProjectUpdateProjectRQ{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) GetUsers() map[string]string {
	if o == nil || IsNil(o.Users) {
		var ret map[string]string
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) GetUsersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given map[string]string and assigns it to the Users field.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) SetUsers(v map[string]string) {
	o.Users = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) GetConfiguration() ComEpamReportportalBaseModelProjectConfigProjectConfigurationUpdate {
	if o == nil || IsNil(o.Configuration) {
		var ret ComEpamReportportalBaseModelProjectConfigProjectConfigurationUpdate
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) GetConfigurationOk() (*ComEpamReportportalBaseModelProjectConfigProjectConfigurationUpdate, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given ComEpamReportportalBaseModelProjectConfigProjectConfigurationUpdate and assigns it to the Configuration field.
func (o *ComEpamReportportalBaseModelProjectUpdateProjectRQ) SetConfiguration(v ComEpamReportportalBaseModelProjectConfigProjectConfigurationUpdate) {
	o.Configuration = &v
}

func (o ComEpamReportportalBaseModelProjectUpdateProjectRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelProjectUpdateProjectRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseModelProjectUpdateProjectRQ struct {
	value *ComEpamReportportalBaseModelProjectUpdateProjectRQ
	isSet bool
}

func (v NullableComEpamReportportalBaseModelProjectUpdateProjectRQ) Get() *ComEpamReportportalBaseModelProjectUpdateProjectRQ {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelProjectUpdateProjectRQ) Set(val *ComEpamReportportalBaseModelProjectUpdateProjectRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelProjectUpdateProjectRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelProjectUpdateProjectRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelProjectUpdateProjectRQ(val *ComEpamReportportalBaseModelProjectUpdateProjectRQ) *NullableComEpamReportportalBaseModelProjectUpdateProjectRQ {
	return &NullableComEpamReportportalBaseModelProjectUpdateProjectRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelProjectUpdateProjectRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelProjectUpdateProjectRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
