/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseModelProjectProjectResourceProjectUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelProjectProjectResourceProjectUser{}

// ComEpamReportportalBaseModelProjectProjectResourceProjectUser struct for ComEpamReportportalBaseModelProjectProjectResourceProjectUser
type ComEpamReportportalBaseModelProjectProjectResourceProjectUser struct {
	Uuid        *string `json:"uuid,omitempty"`
	Login       *string `json:"login,omitempty"`
	Email       *string `json:"email,omitempty"`
	ProjectRole *string `json:"projectRole,omitempty"`
	AccountRole *string `json:"accountRole,omitempty"`
	AccountType *string `json:"accountType,omitempty"`
}

// NewComEpamReportportalBaseModelProjectProjectResourceProjectUser instantiates a new ComEpamReportportalBaseModelProjectProjectResourceProjectUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelProjectProjectResourceProjectUser() *ComEpamReportportalBaseModelProjectProjectResourceProjectUser {
	this := ComEpamReportportalBaseModelProjectProjectResourceProjectUser{}
	return &this
}

// NewComEpamReportportalBaseModelProjectProjectResourceProjectUserWithDefaults instantiates a new ComEpamReportportalBaseModelProjectProjectResourceProjectUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelProjectProjectResourceProjectUserWithDefaults() *ComEpamReportportalBaseModelProjectProjectResourceProjectUser {
	this := ComEpamReportportalBaseModelProjectProjectResourceProjectUser{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) SetUuid(v string) {
	o.Uuid = &v
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetLogin() string {
	if o == nil || IsNil(o.Login) {
		var ret string
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetLoginOk() (*string, bool) {
	if o == nil || IsNil(o.Login) {
		return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) HasLogin() bool {
	if o != nil && !IsNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given string and assigns it to the Login field.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) SetLogin(v string) {
	o.Login = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) SetEmail(v string) {
	o.Email = &v
}

// GetProjectRole returns the ProjectRole field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetProjectRole() string {
	if o == nil || IsNil(o.ProjectRole) {
		var ret string
		return ret
	}
	return *o.ProjectRole
}

// GetProjectRoleOk returns a tuple with the ProjectRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetProjectRoleOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectRole) {
		return nil, false
	}
	return o.ProjectRole, true
}

// HasProjectRole returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) HasProjectRole() bool {
	if o != nil && !IsNil(o.ProjectRole) {
		return true
	}

	return false
}

// SetProjectRole gets a reference to the given string and assigns it to the ProjectRole field.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) SetProjectRole(v string) {
	o.ProjectRole = &v
}

// GetAccountRole returns the AccountRole field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetAccountRole() string {
	if o == nil || IsNil(o.AccountRole) {
		var ret string
		return ret
	}
	return *o.AccountRole
}

// GetAccountRoleOk returns a tuple with the AccountRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetAccountRoleOk() (*string, bool) {
	if o == nil || IsNil(o.AccountRole) {
		return nil, false
	}
	return o.AccountRole, true
}

// HasAccountRole returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) HasAccountRole() bool {
	if o != nil && !IsNil(o.AccountRole) {
		return true
	}

	return false
}

// SetAccountRole gets a reference to the given string and assigns it to the AccountRole field.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) SetAccountRole(v string) {
	o.AccountRole = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) SetAccountType(v string) {
	o.AccountType = &v
}

func (o ComEpamReportportalBaseModelProjectProjectResourceProjectUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelProjectProjectResourceProjectUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.ProjectRole) {
		toSerialize["projectRole"] = o.ProjectRole
	}
	if !IsNil(o.AccountRole) {
		toSerialize["accountRole"] = o.AccountRole
	}
	if !IsNil(o.AccountType) {
		toSerialize["accountType"] = o.AccountType
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser struct {
	value *ComEpamReportportalBaseModelProjectProjectResourceProjectUser
	isSet bool
}

func (v NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser) Get() *ComEpamReportportalBaseModelProjectProjectResourceProjectUser {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser) Set(val *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelProjectProjectResourceProjectUser(val *ComEpamReportportalBaseModelProjectProjectResourceProjectUser) *NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser {
	return &NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelProjectProjectResourceProjectUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
