/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ{}

// ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ struct for ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ
type ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ struct {
	TypeRef   string `json:"typeRef"`
	LongName  string `json:"longName"`
	ShortName string `json:"shortName"`
	Color     string `json:"color" validate:"regexp=#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"`
}

type _ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ

// NewComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ instantiates a new ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ(typeRef string, longName string, shortName string, color string) *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ {
	this := ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ{}
	this.TypeRef = typeRef
	this.LongName = longName
	this.ShortName = shortName
	this.Color = color
	return &this
}

// NewComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQWithDefaults instantiates a new ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQWithDefaults() *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ {
	this := ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ{}
	return &this
}

// GetTypeRef returns the TypeRef field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetTypeRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeRef
}

// GetTypeRefOk returns a tuple with the TypeRef field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetTypeRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeRef, true
}

// SetTypeRef sets field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) SetTypeRef(v string) {
	o.TypeRef = v
}

// GetLongName returns the LongName field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetLongName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LongName
}

// GetLongNameOk returns a tuple with the LongName field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetLongNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LongName, true
}

// SetLongName sets field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) SetLongName(v string) {
	o.LongName = v
}

// GetShortName returns the ShortName field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetShortName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShortName
}

// GetShortNameOk returns a tuple with the ShortName field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetShortNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShortName, true
}

// SetShortName sets field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) SetShortName(v string) {
	o.ShortName = v
}

// GetColor returns the Color field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Color
}

// GetColorOk returns a tuple with the Color field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Color, true
}

// SetColor sets field value
func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) SetColor(v string) {
	o.Color = v
}

func (o ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["typeRef"] = o.TypeRef
	toSerialize["longName"] = o.LongName
	toSerialize["shortName"] = o.ShortName
	toSerialize["color"] = o.Color
	return toSerialize, nil
}

func (o *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"typeRef",
		"longName",
		"shortName",
		"color",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ := _ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ)

	if err != nil {
		return err
	}

	*o = ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ(varComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ)

	return err
}

type NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ struct {
	value *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ
	isSet bool
}

func (v NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) Get() *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) Set(val *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ(val *ComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) *NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ {
	return &NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelProjectConfigCreateIssueSubTypeRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
