/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalApiModelOrganizationStatsRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalApiModelOrganizationStatsRelationships{}

// ComEpamReportportalApiModelOrganizationStatsRelationships struct for ComEpamReportportalApiModelOrganizationStatsRelationships
type ComEpamReportportalApiModelOrganizationStatsRelationships struct {
	Users    *OrganizationStatsRelationshipsUsers    `json:"users,omitempty"`
	Projects *OrganizationStatsRelationshipsProjects `json:"projects,omitempty"`
	Launches *OrganizationStatsRelationshipsLaunches `json:"launches,omitempty"`
	Billing  *OrganizationStatsRelationshipsBilling  `json:"billing,omitempty"`
}

// NewComEpamReportportalApiModelOrganizationStatsRelationships instantiates a new ComEpamReportportalApiModelOrganizationStatsRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalApiModelOrganizationStatsRelationships() *ComEpamReportportalApiModelOrganizationStatsRelationships {
	this := ComEpamReportportalApiModelOrganizationStatsRelationships{}
	return &this
}

// NewComEpamReportportalApiModelOrganizationStatsRelationshipsWithDefaults instantiates a new ComEpamReportportalApiModelOrganizationStatsRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalApiModelOrganizationStatsRelationshipsWithDefaults() *ComEpamReportportalApiModelOrganizationStatsRelationships {
	this := ComEpamReportportalApiModelOrganizationStatsRelationships{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetUsers() OrganizationStatsRelationshipsUsers {
	if o == nil || IsNil(o.Users) {
		var ret OrganizationStatsRelationshipsUsers
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetUsersOk() (*OrganizationStatsRelationshipsUsers, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given OrganizationStatsRelationshipsUsers and assigns it to the Users field.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) SetUsers(v OrganizationStatsRelationshipsUsers) {
	o.Users = &v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetProjects() OrganizationStatsRelationshipsProjects {
	if o == nil || IsNil(o.Projects) {
		var ret OrganizationStatsRelationshipsProjects
		return ret
	}
	return *o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetProjectsOk() (*OrganizationStatsRelationshipsProjects, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given OrganizationStatsRelationshipsProjects and assigns it to the Projects field.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) SetProjects(v OrganizationStatsRelationshipsProjects) {
	o.Projects = &v
}

// GetLaunches returns the Launches field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetLaunches() OrganizationStatsRelationshipsLaunches {
	if o == nil || IsNil(o.Launches) {
		var ret OrganizationStatsRelationshipsLaunches
		return ret
	}
	return *o.Launches
}

// GetLaunchesOk returns a tuple with the Launches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetLaunchesOk() (*OrganizationStatsRelationshipsLaunches, bool) {
	if o == nil || IsNil(o.Launches) {
		return nil, false
	}
	return o.Launches, true
}

// HasLaunches returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) HasLaunches() bool {
	if o != nil && !IsNil(o.Launches) {
		return true
	}

	return false
}

// SetLaunches gets a reference to the given OrganizationStatsRelationshipsLaunches and assigns it to the Launches field.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) SetLaunches(v OrganizationStatsRelationshipsLaunches) {
	o.Launches = &v
}

// GetBilling returns the Billing field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetBilling() OrganizationStatsRelationshipsBilling {
	if o == nil || IsNil(o.Billing) {
		var ret OrganizationStatsRelationshipsBilling
		return ret
	}
	return *o.Billing
}

// GetBillingOk returns a tuple with the Billing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) GetBillingOk() (*OrganizationStatsRelationshipsBilling, bool) {
	if o == nil || IsNil(o.Billing) {
		return nil, false
	}
	return o.Billing, true
}

// HasBilling returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) HasBilling() bool {
	if o != nil && !IsNil(o.Billing) {
		return true
	}

	return false
}

// SetBilling gets a reference to the given OrganizationStatsRelationshipsBilling and assigns it to the Billing field.
func (o *ComEpamReportportalApiModelOrganizationStatsRelationships) SetBilling(v OrganizationStatsRelationshipsBilling) {
	o.Billing = &v
}

func (o ComEpamReportportalApiModelOrganizationStatsRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalApiModelOrganizationStatsRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	if !IsNil(o.Launches) {
		toSerialize["launches"] = o.Launches
	}
	if !IsNil(o.Billing) {
		toSerialize["billing"] = o.Billing
	}
	return toSerialize, nil
}

type NullableComEpamReportportalApiModelOrganizationStatsRelationships struct {
	value *ComEpamReportportalApiModelOrganizationStatsRelationships
	isSet bool
}

func (v NullableComEpamReportportalApiModelOrganizationStatsRelationships) Get() *ComEpamReportportalApiModelOrganizationStatsRelationships {
	return v.value
}

func (v *NullableComEpamReportportalApiModelOrganizationStatsRelationships) Set(val *ComEpamReportportalApiModelOrganizationStatsRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalApiModelOrganizationStatsRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalApiModelOrganizationStatsRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalApiModelOrganizationStatsRelationships(val *ComEpamReportportalApiModelOrganizationStatsRelationships) *NullableComEpamReportportalApiModelOrganizationStatsRelationships {
	return &NullableComEpamReportportalApiModelOrganizationStatsRelationships{value: val, isSet: true}
}

func (v NullableComEpamReportportalApiModelOrganizationStatsRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalApiModelOrganizationStatsRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
