/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalApiModelSearchCriteriaRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalApiModelSearchCriteriaRQ{}

// ComEpamReportportalApiModelSearchCriteriaRQ This is a [GET with body payload](https://opensource.zalando.com/restful-api-guidelines/#get-with-body)  that doesn't create resources.  It returns all activities matching the query passed as the request input payload.
type ComEpamReportportalApiModelSearchCriteriaRQ struct {
	// The offset used for this page of results.
	Offset *int32 `json:"offset,omitempty"`
	// The limit used for this page of results.  This will be the same as the limit query parameter unless it exceeded the maximum value allowed for this API endpoint.
	Limit *int32 `json:"limit,omitempty"`
	// Field to define the sort field.
	Sort           *string                                                        `json:"sort,omitempty"`
	Order          *string                                                        `json:"order,omitempty"`
	SearchCriteria []ComEpamReportportalApiModelSearchCriteriaSearchCriteriaInner `json:"search_criteria,omitempty"`
}

// NewComEpamReportportalApiModelSearchCriteriaRQ instantiates a new ComEpamReportportalApiModelSearchCriteriaRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalApiModelSearchCriteriaRQ() *ComEpamReportportalApiModelSearchCriteriaRQ {
	this := ComEpamReportportalApiModelSearchCriteriaRQ{}
	return &this
}

// NewComEpamReportportalApiModelSearchCriteriaRQWithDefaults instantiates a new ComEpamReportportalApiModelSearchCriteriaRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalApiModelSearchCriteriaRQWithDefaults() *ComEpamReportportalApiModelSearchCriteriaRQ {
	this := ComEpamReportportalApiModelSearchCriteriaRQ{}
	return &this
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) SetLimit(v int32) {
	o.Limit = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetSort() string {
	if o == nil || IsNil(o.Sort) {
		var ret string
		return ret
	}
	return *o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetSortOk() (*string, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given string and assigns it to the Sort field.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) SetSort(v string) {
	o.Sort = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) SetOrder(v string) {
	o.Order = &v
}

// GetSearchCriteria returns the SearchCriteria field value if set, zero value otherwise.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetSearchCriteria() []ComEpamReportportalApiModelSearchCriteriaSearchCriteriaInner {
	if o == nil || IsNil(o.SearchCriteria) {
		var ret []ComEpamReportportalApiModelSearchCriteriaSearchCriteriaInner
		return ret
	}
	return o.SearchCriteria
}

// GetSearchCriteriaOk returns a tuple with the SearchCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) GetSearchCriteriaOk() ([]ComEpamReportportalApiModelSearchCriteriaSearchCriteriaInner, bool) {
	if o == nil || IsNil(o.SearchCriteria) {
		return nil, false
	}
	return o.SearchCriteria, true
}

// HasSearchCriteria returns a boolean if a field has been set.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) HasSearchCriteria() bool {
	if o != nil && !IsNil(o.SearchCriteria) {
		return true
	}

	return false
}

// SetSearchCriteria gets a reference to the given []ComEpamReportportalApiModelSearchCriteriaSearchCriteriaInner and assigns it to the SearchCriteria field.
func (o *ComEpamReportportalApiModelSearchCriteriaRQ) SetSearchCriteria(v []ComEpamReportportalApiModelSearchCriteriaSearchCriteriaInner) {
	o.SearchCriteria = v
}

func (o ComEpamReportportalApiModelSearchCriteriaRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalApiModelSearchCriteriaRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.SearchCriteria) {
		toSerialize["search_criteria"] = o.SearchCriteria
	}
	return toSerialize, nil
}

type NullableComEpamReportportalApiModelSearchCriteriaRQ struct {
	value *ComEpamReportportalApiModelSearchCriteriaRQ
	isSet bool
}

func (v NullableComEpamReportportalApiModelSearchCriteriaRQ) Get() *ComEpamReportportalApiModelSearchCriteriaRQ {
	return v.value
}

func (v *NullableComEpamReportportalApiModelSearchCriteriaRQ) Set(val *ComEpamReportportalApiModelSearchCriteriaRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalApiModelSearchCriteriaRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalApiModelSearchCriteriaRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalApiModelSearchCriteriaRQ(val *ComEpamReportportalApiModelSearchCriteriaRQ) *NullableComEpamReportportalApiModelSearchCriteriaRQ {
	return &NullableComEpamReportportalApiModelSearchCriteriaRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalApiModelSearchCriteriaRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalApiModelSearchCriteriaRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
