/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ComEpamReportportalBaseModelUserEditUserRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelUserEditUserRQ{}

// ComEpamReportportalBaseModelUserEditUserRQ struct for ComEpamReportportalBaseModelUserEditUserRQ
type ComEpamReportportalBaseModelUserEditUserRQ struct {
	Email       string  `json:"email"`
	ExternalId  *string `json:"externalId,omitempty"`
	Active      *bool   `json:"active,omitempty"`
	Role        *string `json:"role,omitempty"`
	AccountType *string `json:"accountType,omitempty"`
	FullName    string  `json:"fullName" validate:"regexp=^[A-Za-z0-9.'_\\\\- ]+$"`
}

type _ComEpamReportportalBaseModelUserEditUserRQ ComEpamReportportalBaseModelUserEditUserRQ

// NewComEpamReportportalBaseModelUserEditUserRQ instantiates a new ComEpamReportportalBaseModelUserEditUserRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelUserEditUserRQ(email string, fullName string) *ComEpamReportportalBaseModelUserEditUserRQ {
	this := ComEpamReportportalBaseModelUserEditUserRQ{}
	this.Email = email
	this.FullName = fullName
	return &this
}

// NewComEpamReportportalBaseModelUserEditUserRQWithDefaults instantiates a new ComEpamReportportalBaseModelUserEditUserRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelUserEditUserRQWithDefaults() *ComEpamReportportalBaseModelUserEditUserRQ {
	this := ComEpamReportportalBaseModelUserEditUserRQ{}
	return &this
}

// GetEmail returns the Email field value
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ComEpamReportportalBaseModelUserEditUserRQ) SetEmail(v string) {
	o.Email = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetExternalIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) SetActive(v bool) {
	o.Active = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) SetRole(v string) {
	o.Role = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) SetAccountType(v string) {
	o.AccountType = &v
}

// GetFullName returns the FullName field value
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelUserEditUserRQ) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *ComEpamReportportalBaseModelUserEditUserRQ) SetFullName(v string) {
	o.FullName = v
}

func (o ComEpamReportportalBaseModelUserEditUserRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelUserEditUserRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.ExternalId) {
		toSerialize["externalId"] = o.ExternalId
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.AccountType) {
		toSerialize["accountType"] = o.AccountType
	}
	toSerialize["fullName"] = o.FullName
	return toSerialize, nil
}

func (o *ComEpamReportportalBaseModelUserEditUserRQ) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"fullName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComEpamReportportalBaseModelUserEditUserRQ := _ComEpamReportportalBaseModelUserEditUserRQ{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComEpamReportportalBaseModelUserEditUserRQ)

	if err != nil {
		return err
	}

	*o = ComEpamReportportalBaseModelUserEditUserRQ(varComEpamReportportalBaseModelUserEditUserRQ)

	return err
}

type NullableComEpamReportportalBaseModelUserEditUserRQ struct {
	value *ComEpamReportportalBaseModelUserEditUserRQ
	isSet bool
}

func (v NullableComEpamReportportalBaseModelUserEditUserRQ) Get() *ComEpamReportportalBaseModelUserEditUserRQ {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelUserEditUserRQ) Set(val *ComEpamReportportalBaseModelUserEditUserRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelUserEditUserRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelUserEditUserRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelUserEditUserRQ(val *ComEpamReportportalBaseModelUserEditUserRQ) *NullableComEpamReportportalBaseModelUserEditUserRQ {
	return &NullableComEpamReportportalBaseModelUserEditUserRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelUserEditUserRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelUserEditUserRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
