/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ{}

// ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ struct for ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ
type ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ struct {
	ComEpamReportportalBaseCoreTmsDtoTmsManualScenarioRQ
	Steps []ComEpamReportportalBaseCoreTmsDtoTmsStepRQ `json:"steps,omitempty"`
}

type _ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ

// NewComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ instantiates a new ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ(manualScenarioType string) *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ {
	this := ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ{}
	this.ManualScenarioType = manualScenarioType
	return &this
}

// NewComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQWithDefaults instantiates a new ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQWithDefaults() *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ {
	this := ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ{}
	return &this
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) GetSteps() []ComEpamReportportalBaseCoreTmsDtoTmsStepRQ {
	if o == nil || IsNil(o.Steps) {
		var ret []ComEpamReportportalBaseCoreTmsDtoTmsStepRQ
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) GetStepsOk() ([]ComEpamReportportalBaseCoreTmsDtoTmsStepRQ, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []ComEpamReportportalBaseCoreTmsDtoTmsStepRQ and assigns it to the Steps field.
func (o *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) SetSteps(v []ComEpamReportportalBaseCoreTmsDtoTmsStepRQ) {
	o.Steps = v
}

func (o ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	return toSerialize, nil
}

func (o *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"manualScenarioType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ := _ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ)

	if err != nil {
		return err
	}

	*o = ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ(varComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ)

	return err
}

type NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ struct {
	value *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ
	isSet bool
}

func (v NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) Get() *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ {
	return v.value
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) Set(val *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ(val *ComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) *NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ {
	return &NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoTmsStepsManualScenarioRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
