/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel{}

// ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel struct for ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel
type ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel struct {
	WidgetName     *string                               `json:"widgetName,omitempty"`
	WidgetId       int64                                 `json:"widgetId"`
	WidgetType     *string                               `json:"widgetType,omitempty"`
	WidgetSize     *ComEpamReportportalBaseModelSize     `json:"widgetSize,omitempty"`
	WidgetPosition *ComEpamReportportalBaseModelPosition `json:"widgetPosition,omitempty"`
	WidgetOptions  map[string]interface{}                `json:"widgetOptions,omitempty"`
}

type _ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel

// NewComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel instantiates a new ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel(widgetId int64) *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel {
	this := ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel{}
	this.WidgetId = widgetId
	return &this
}

// NewComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModelWithDefaults instantiates a new ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModelWithDefaults() *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel {
	this := ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel{}
	return &this
}

// GetWidgetName returns the WidgetName field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetName() string {
	if o == nil || IsNil(o.WidgetName) {
		var ret string
		return ret
	}
	return *o.WidgetName
}

// GetWidgetNameOk returns a tuple with the WidgetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetNameOk() (*string, bool) {
	if o == nil || IsNil(o.WidgetName) {
		return nil, false
	}
	return o.WidgetName, true
}

// HasWidgetName returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) HasWidgetName() bool {
	if o != nil && !IsNil(o.WidgetName) {
		return true
	}

	return false
}

// SetWidgetName gets a reference to the given string and assigns it to the WidgetName field.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) SetWidgetName(v string) {
	o.WidgetName = &v
}

// GetWidgetId returns the WidgetId field value
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WidgetId
}

// GetWidgetIdOk returns a tuple with the WidgetId field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WidgetId, true
}

// SetWidgetId sets field value
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) SetWidgetId(v int64) {
	o.WidgetId = v
}

// GetWidgetType returns the WidgetType field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetType() string {
	if o == nil || IsNil(o.WidgetType) {
		var ret string
		return ret
	}
	return *o.WidgetType
}

// GetWidgetTypeOk returns a tuple with the WidgetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WidgetType) {
		return nil, false
	}
	return o.WidgetType, true
}

// HasWidgetType returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) HasWidgetType() bool {
	if o != nil && !IsNil(o.WidgetType) {
		return true
	}

	return false
}

// SetWidgetType gets a reference to the given string and assigns it to the WidgetType field.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) SetWidgetType(v string) {
	o.WidgetType = &v
}

// GetWidgetSize returns the WidgetSize field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetSize() ComEpamReportportalBaseModelSize {
	if o == nil || IsNil(o.WidgetSize) {
		var ret ComEpamReportportalBaseModelSize
		return ret
	}
	return *o.WidgetSize
}

// GetWidgetSizeOk returns a tuple with the WidgetSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetSizeOk() (*ComEpamReportportalBaseModelSize, bool) {
	if o == nil || IsNil(o.WidgetSize) {
		return nil, false
	}
	return o.WidgetSize, true
}

// HasWidgetSize returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) HasWidgetSize() bool {
	if o != nil && !IsNil(o.WidgetSize) {
		return true
	}

	return false
}

// SetWidgetSize gets a reference to the given ComEpamReportportalBaseModelSize and assigns it to the WidgetSize field.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) SetWidgetSize(v ComEpamReportportalBaseModelSize) {
	o.WidgetSize = &v
}

// GetWidgetPosition returns the WidgetPosition field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetPosition() ComEpamReportportalBaseModelPosition {
	if o == nil || IsNil(o.WidgetPosition) {
		var ret ComEpamReportportalBaseModelPosition
		return ret
	}
	return *o.WidgetPosition
}

// GetWidgetPositionOk returns a tuple with the WidgetPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetPositionOk() (*ComEpamReportportalBaseModelPosition, bool) {
	if o == nil || IsNil(o.WidgetPosition) {
		return nil, false
	}
	return o.WidgetPosition, true
}

// HasWidgetPosition returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) HasWidgetPosition() bool {
	if o != nil && !IsNil(o.WidgetPosition) {
		return true
	}

	return false
}

// SetWidgetPosition gets a reference to the given ComEpamReportportalBaseModelPosition and assigns it to the WidgetPosition field.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) SetWidgetPosition(v ComEpamReportportalBaseModelPosition) {
	o.WidgetPosition = &v
}

// GetWidgetOptions returns the WidgetOptions field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetOptions() map[string]interface{} {
	if o == nil || IsNil(o.WidgetOptions) {
		var ret map[string]interface{}
		return ret
	}
	return o.WidgetOptions
}

// GetWidgetOptionsOk returns a tuple with the WidgetOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) GetWidgetOptionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.WidgetOptions) {
		return map[string]interface{}{}, false
	}
	return o.WidgetOptions, true
}

// HasWidgetOptions returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) HasWidgetOptions() bool {
	if o != nil && !IsNil(o.WidgetOptions) {
		return true
	}

	return false
}

// SetWidgetOptions gets a reference to the given map[string]interface{} and assigns it to the WidgetOptions field.
func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) SetWidgetOptions(v map[string]interface{}) {
	o.WidgetOptions = v
}

func (o ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WidgetName) {
		toSerialize["widgetName"] = o.WidgetName
	}
	toSerialize["widgetId"] = o.WidgetId
	if !IsNil(o.WidgetType) {
		toSerialize["widgetType"] = o.WidgetType
	}
	if !IsNil(o.WidgetSize) {
		toSerialize["widgetSize"] = o.WidgetSize
	}
	if !IsNil(o.WidgetPosition) {
		toSerialize["widgetPosition"] = o.WidgetPosition
	}
	if !IsNil(o.WidgetOptions) {
		toSerialize["widgetOptions"] = o.WidgetOptions
	}
	return toSerialize, nil
}

func (o *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"widgetId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel := _ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel)

	if err != nil {
		return err
	}

	*o = ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel(varComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel)

	return err
}

type NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel struct {
	value *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel
	isSet bool
}

func (v NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) Get() *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) Set(val *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel(val *ComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) *NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel {
	return &NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelDashboardDashboardResourceWidgetObjectModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
