/*
ReportPortal

ReportPortal API documentation

API version: develop-322
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateDashboardRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDashboardRQ{}

// CreateDashboardRQ struct for CreateDashboardRQ
type CreateDashboardRQ struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

type _CreateDashboardRQ CreateDashboardRQ

// NewCreateDashboardRQ instantiates a new CreateDashboardRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDashboardRQ(name string) *CreateDashboardRQ {
	this := CreateDashboardRQ{}
	this.Name = name
	return &this
}

// NewCreateDashboardRQWithDefaults instantiates a new CreateDashboardRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDashboardRQWithDefaults() *CreateDashboardRQ {
	this := CreateDashboardRQ{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateDashboardRQ) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDashboardRQ) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateDashboardRQ) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateDashboardRQ) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value
func (o *CreateDashboardRQ) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDashboardRQ) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDashboardRQ) SetName(v string) {
	o.Name = v
}

func (o CreateDashboardRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDashboardRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateDashboardRQ) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDashboardRQ := _CreateDashboardRQ{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDashboardRQ)

	if err != nil {
		return err
	}

	*o = CreateDashboardRQ(varCreateDashboardRQ)

	return err
}

type NullableCreateDashboardRQ struct {
	value *CreateDashboardRQ
	isSet bool
}

func (v NullableCreateDashboardRQ) Get() *CreateDashboardRQ {
	return v.value
}

func (v *NullableCreateDashboardRQ) Set(val *CreateDashboardRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDashboardRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDashboardRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDashboardRQ(val *CreateDashboardRQ) *NullableCreateDashboardRQ {
	return &NullableCreateDashboardRQ{value: val, isSet: true}
}

func (v NullableCreateDashboardRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDashboardRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
