/*
ReportPortal

ReportPortal API documentation

API version: 5.14.4
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RestorePasswordRQ type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestorePasswordRQ{}

// RestorePasswordRQ struct for RestorePasswordRQ
type RestorePasswordRQ struct {
	Email string `json:"email"`
}

type _RestorePasswordRQ RestorePasswordRQ

// NewRestorePasswordRQ instantiates a new RestorePasswordRQ object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestorePasswordRQ(email string) *RestorePasswordRQ {
	this := RestorePasswordRQ{}
	this.Email = email
	return &this
}

// NewRestorePasswordRQWithDefaults instantiates a new RestorePasswordRQ object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestorePasswordRQWithDefaults() *RestorePasswordRQ {
	this := RestorePasswordRQ{}
	return &this
}

// GetEmail returns the Email field value
func (o *RestorePasswordRQ) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RestorePasswordRQ) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RestorePasswordRQ) SetEmail(v string) {
	o.Email = v
}

func (o RestorePasswordRQ) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestorePasswordRQ) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *RestorePasswordRQ) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestorePasswordRQ := _RestorePasswordRQ{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestorePasswordRQ)

	if err != nil {
		return err
	}

	*o = RestorePasswordRQ(varRestorePasswordRQ)

	return err
}

type NullableRestorePasswordRQ struct {
	value *RestorePasswordRQ
	isSet bool
}

func (v NullableRestorePasswordRQ) Get() *RestorePasswordRQ {
	return v.value
}

func (v *NullableRestorePasswordRQ) Set(val *RestorePasswordRQ) {
	v.value = val
	v.isSet = true
}

func (v NullableRestorePasswordRQ) IsSet() bool {
	return v.isSet
}

func (v *NullableRestorePasswordRQ) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestorePasswordRQ(val *RestorePasswordRQ) *NullableRestorePasswordRQ {
	return &NullableRestorePasswordRQ{value: val, isSet: true}
}

func (v NullableRestorePasswordRQ) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestorePasswordRQ) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
