/*
ReportPortal

ReportPortal API documentation

API version: develop-322
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserFilterResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserFilterResource{}

// UserFilterResource struct for UserFilterResource
type UserFilterResource struct {
	Description *string               `json:"description,omitempty"`
	Owner       string                `json:"owner"`
	Id          int64                 `json:"id"`
	Name        string                `json:"name"`
	Conditions  []UserFilterCondition `json:"conditions"`
	Orders      []Order               `json:"orders"`
	Type        string                `json:"type"`
}

type _UserFilterResource UserFilterResource

// NewUserFilterResource instantiates a new UserFilterResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserFilterResource(owner string, id int64, name string, conditions []UserFilterCondition, orders []Order, type_ string) *UserFilterResource {
	this := UserFilterResource{}
	this.Owner = owner
	this.Id = id
	this.Name = name
	this.Conditions = conditions
	this.Orders = orders
	this.Type = type_
	return &this
}

// NewUserFilterResourceWithDefaults instantiates a new UserFilterResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserFilterResourceWithDefaults() *UserFilterResource {
	this := UserFilterResource{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UserFilterResource) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserFilterResource) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UserFilterResource) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UserFilterResource) SetDescription(v string) {
	o.Description = &v
}

// GetOwner returns the Owner field value
func (o *UserFilterResource) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *UserFilterResource) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *UserFilterResource) SetOwner(v string) {
	o.Owner = v
}

// GetId returns the Id field value
func (o *UserFilterResource) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserFilterResource) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserFilterResource) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *UserFilterResource) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserFilterResource) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserFilterResource) SetName(v string) {
	o.Name = v
}

// GetConditions returns the Conditions field value
func (o *UserFilterResource) GetConditions() []UserFilterCondition {
	if o == nil {
		var ret []UserFilterCondition
		return ret
	}

	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value
// and a boolean to check if the value has been set.
func (o *UserFilterResource) GetConditionsOk() ([]UserFilterCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conditions, true
}

// SetConditions sets field value
func (o *UserFilterResource) SetConditions(v []UserFilterCondition) {
	o.Conditions = v
}

// GetOrders returns the Orders field value
func (o *UserFilterResource) GetOrders() []Order {
	if o == nil {
		var ret []Order
		return ret
	}

	return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value
// and a boolean to check if the value has been set.
func (o *UserFilterResource) GetOrdersOk() ([]Order, bool) {
	if o == nil {
		return nil, false
	}
	return o.Orders, true
}

// SetOrders sets field value
func (o *UserFilterResource) SetOrders(v []Order) {
	o.Orders = v
}

// GetType returns the Type field value
func (o *UserFilterResource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UserFilterResource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UserFilterResource) SetType(v string) {
	o.Type = v
}

func (o UserFilterResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserFilterResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["owner"] = o.Owner
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["conditions"] = o.Conditions
	toSerialize["orders"] = o.Orders
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *UserFilterResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"owner",
		"id",
		"name",
		"conditions",
		"orders",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserFilterResource := _UserFilterResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserFilterResource)

	if err != nil {
		return err
	}

	*o = UserFilterResource(varUserFilterResource)

	return err
}

type NullableUserFilterResource struct {
	value *UserFilterResource
	isSet bool
}

func (v NullableUserFilterResource) Get() *UserFilterResource {
	return v.value
}

func (v *NullableUserFilterResource) Set(val *UserFilterResource) {
	v.value = val
	v.isSet = true
}

func (v NullableUserFilterResource) IsSet() bool {
	return v.isSet
}

func (v *NullableUserFilterResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserFilterResource(val *UserFilterResource) *NullableUserFilterResource {
	return &NullableUserFilterResource{value: val, isSet: true}
}

func (v NullableUserFilterResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserFilterResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
