/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ComEpamReportportalBaseReportingIssueExternalSystemIssue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseReportingIssueExternalSystemIssue{}

// ComEpamReportportalBaseReportingIssueExternalSystemIssue struct for ComEpamReportportalBaseReportingIssueExternalSystemIssue
type ComEpamReportportalBaseReportingIssueExternalSystemIssue struct {
	TicketId   string     `json:"ticketId"`
	SubmitDate *time.Time `json:"submitDate,omitempty"`
	BtsUrl     string     `json:"btsUrl"`
	BtsProject string     `json:"btsProject"`
	Url        string     `json:"url"`
	PluginName *string    `json:"pluginName,omitempty"`
}

type _ComEpamReportportalBaseReportingIssueExternalSystemIssue ComEpamReportportalBaseReportingIssueExternalSystemIssue

// NewComEpamReportportalBaseReportingIssueExternalSystemIssue instantiates a new ComEpamReportportalBaseReportingIssueExternalSystemIssue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseReportingIssueExternalSystemIssue(ticketId string, btsUrl string, btsProject string, url string) *ComEpamReportportalBaseReportingIssueExternalSystemIssue {
	this := ComEpamReportportalBaseReportingIssueExternalSystemIssue{}
	this.TicketId = ticketId
	this.BtsUrl = btsUrl
	this.BtsProject = btsProject
	this.Url = url
	return &this
}

// NewComEpamReportportalBaseReportingIssueExternalSystemIssueWithDefaults instantiates a new ComEpamReportportalBaseReportingIssueExternalSystemIssue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseReportingIssueExternalSystemIssueWithDefaults() *ComEpamReportportalBaseReportingIssueExternalSystemIssue {
	this := ComEpamReportportalBaseReportingIssueExternalSystemIssue{}
	return &this
}

// GetTicketId returns the TicketId field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetTicketId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TicketId
}

// GetTicketIdOk returns a tuple with the TicketId field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetTicketIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TicketId, true
}

// SetTicketId sets field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) SetTicketId(v string) {
	o.TicketId = v
}

// GetSubmitDate returns the SubmitDate field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetSubmitDate() time.Time {
	if o == nil || IsNil(o.SubmitDate) {
		var ret time.Time
		return ret
	}
	return *o.SubmitDate
}

// GetSubmitDateOk returns a tuple with the SubmitDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetSubmitDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SubmitDate) {
		return nil, false
	}
	return o.SubmitDate, true
}

// HasSubmitDate returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) HasSubmitDate() bool {
	if o != nil && !IsNil(o.SubmitDate) {
		return true
	}

	return false
}

// SetSubmitDate gets a reference to the given time.Time and assigns it to the SubmitDate field.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) SetSubmitDate(v time.Time) {
	o.SubmitDate = &v
}

// GetBtsUrl returns the BtsUrl field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetBtsUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BtsUrl
}

// GetBtsUrlOk returns a tuple with the BtsUrl field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetBtsUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BtsUrl, true
}

// SetBtsUrl sets field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) SetBtsUrl(v string) {
	o.BtsUrl = v
}

// GetBtsProject returns the BtsProject field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetBtsProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BtsProject
}

// GetBtsProjectOk returns a tuple with the BtsProject field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetBtsProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BtsProject, true
}

// SetBtsProject sets field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) SetBtsProject(v string) {
	o.BtsProject = v
}

// GetUrl returns the Url field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) SetUrl(v string) {
	o.Url = v
}

// GetPluginName returns the PluginName field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetPluginName() string {
	if o == nil || IsNil(o.PluginName) {
		var ret string
		return ret
	}
	return *o.PluginName
}

// GetPluginNameOk returns a tuple with the PluginName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) GetPluginNameOk() (*string, bool) {
	if o == nil || IsNil(o.PluginName) {
		return nil, false
	}
	return o.PluginName, true
}

// HasPluginName returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) HasPluginName() bool {
	if o != nil && !IsNil(o.PluginName) {
		return true
	}

	return false
}

// SetPluginName gets a reference to the given string and assigns it to the PluginName field.
func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) SetPluginName(v string) {
	o.PluginName = &v
}

func (o ComEpamReportportalBaseReportingIssueExternalSystemIssue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseReportingIssueExternalSystemIssue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ticketId"] = o.TicketId
	if !IsNil(o.SubmitDate) {
		toSerialize["submitDate"] = o.SubmitDate
	}
	toSerialize["btsUrl"] = o.BtsUrl
	toSerialize["btsProject"] = o.BtsProject
	toSerialize["url"] = o.Url
	if !IsNil(o.PluginName) {
		toSerialize["pluginName"] = o.PluginName
	}
	return toSerialize, nil
}

func (o *ComEpamReportportalBaseReportingIssueExternalSystemIssue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ticketId",
		"btsUrl",
		"btsProject",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComEpamReportportalBaseReportingIssueExternalSystemIssue := _ComEpamReportportalBaseReportingIssueExternalSystemIssue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComEpamReportportalBaseReportingIssueExternalSystemIssue)

	if err != nil {
		return err
	}

	*o = ComEpamReportportalBaseReportingIssueExternalSystemIssue(varComEpamReportportalBaseReportingIssueExternalSystemIssue)

	return err
}

type NullableComEpamReportportalBaseReportingIssueExternalSystemIssue struct {
	value *ComEpamReportportalBaseReportingIssueExternalSystemIssue
	isSet bool
}

func (v NullableComEpamReportportalBaseReportingIssueExternalSystemIssue) Get() *ComEpamReportportalBaseReportingIssueExternalSystemIssue {
	return v.value
}

func (v *NullableComEpamReportportalBaseReportingIssueExternalSystemIssue) Set(val *ComEpamReportportalBaseReportingIssueExternalSystemIssue) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseReportingIssueExternalSystemIssue) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseReportingIssueExternalSystemIssue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseReportingIssueExternalSystemIssue(val *ComEpamReportportalBaseReportingIssueExternalSystemIssue) *NullableComEpamReportportalBaseReportingIssueExternalSystemIssue {
	return &NullableComEpamReportportalBaseReportingIssueExternalSystemIssue{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseReportingIssueExternalSystemIssue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseReportingIssueExternalSystemIssue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
