/*
ReportPortal

ReportPortal API documentation

API version: develop-553
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource{}

// ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource struct for ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource
type ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource struct {
	Content []ComEpamReportportalBaseModelActivityEventResource `json:"content,omitempty"`
	Page    *ComEpamReportportalBaseModelPagePageMetadata       `json:"page,omitempty"`
}

// NewComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource instantiates a new ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource() *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource {
	this := ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource{}
	return &this
}

// NewComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResourceWithDefaults instantiates a new ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResourceWithDefaults() *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource {
	this := ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) GetContent() []ComEpamReportportalBaseModelActivityEventResource {
	if o == nil || IsNil(o.Content) {
		var ret []ComEpamReportportalBaseModelActivityEventResource
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) GetContentOk() ([]ComEpamReportportalBaseModelActivityEventResource, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []ComEpamReportportalBaseModelActivityEventResource and assigns it to the Content field.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) SetContent(v []ComEpamReportportalBaseModelActivityEventResource) {
	o.Content = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) GetPage() ComEpamReportportalBaseModelPagePageMetadata {
	if o == nil || IsNil(o.Page) {
		var ret ComEpamReportportalBaseModelPagePageMetadata
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) GetPageOk() (*ComEpamReportportalBaseModelPagePageMetadata, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given ComEpamReportportalBaseModelPagePageMetadata and assigns it to the Page field.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) SetPage(v ComEpamReportportalBaseModelPagePageMetadata) {
	o.Page = &v
}

func (o ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource struct {
	value *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource
	isSet bool
}

func (v NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) Get() *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) Set(val *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource(val *ComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource {
	return &NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseModelActivityEventResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
