/*
ReportPortal

ReportPortal API documentation

API version: develop-553
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError{}

// ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError struct for ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError
type ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError struct {
	ExecutionId  *int64  `json:"executionId,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

// NewComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError instantiates a new ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError() *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError {
	this := ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError{}
	return &this
}

// NewComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionErrorWithDefaults instantiates a new ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionErrorWithDefaults() *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError {
	this := ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError{}
	return &this
}

// GetExecutionId returns the ExecutionId field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) GetExecutionId() int64 {
	if o == nil || IsNil(o.ExecutionId) {
		var ret int64
		return ret
	}
	return *o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) GetExecutionIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ExecutionId) {
		return nil, false
	}
	return o.ExecutionId, true
}

// HasExecutionId returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) HasExecutionId() bool {
	if o != nil && !IsNil(o.ExecutionId) {
		return true
	}

	return false
}

// SetExecutionId gets a reference to the given int64 and assigns it to the ExecutionId field.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) SetExecutionId(v int64) {
	o.ExecutionId = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

func (o ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExecutionId) {
		toSerialize["executionId"] = o.ExecutionId
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError struct {
	value *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError
	isSet bool
}

func (v NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) Get() *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError {
	return v.value
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) Set(val *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError(val *ComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) *NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError {
	return &NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoBatchBatchDeleteTestCaseExecutionError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
