/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource{}

// ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource struct for ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource
type ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource struct {
	Content []ComEpamReportportalBaseReportingTestItemResource `json:"content,omitempty"`
	Page    *ComEpamReportportalBaseModelPagePageMetadata      `json:"page,omitempty"`
}

// NewComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource instantiates a new ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource() *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource {
	this := ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource{}
	return &this
}

// NewComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResourceWithDefaults instantiates a new ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResourceWithDefaults() *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource {
	this := ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) GetContent() []ComEpamReportportalBaseReportingTestItemResource {
	if o == nil || IsNil(o.Content) {
		var ret []ComEpamReportportalBaseReportingTestItemResource
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) GetContentOk() ([]ComEpamReportportalBaseReportingTestItemResource, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []ComEpamReportportalBaseReportingTestItemResource and assigns it to the Content field.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) SetContent(v []ComEpamReportportalBaseReportingTestItemResource) {
	o.Content = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) GetPage() ComEpamReportportalBaseModelPagePageMetadata {
	if o == nil || IsNil(o.Page) {
		var ret ComEpamReportportalBaseModelPagePageMetadata
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) GetPageOk() (*ComEpamReportportalBaseModelPagePageMetadata, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given ComEpamReportportalBaseModelPagePageMetadata and assigns it to the Page field.
func (o *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) SetPage(v ComEpamReportportalBaseModelPagePageMetadata) {
	o.Page = &v
}

func (o ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource struct {
	value *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource
	isSet bool
}

func (v NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) Get() *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource {
	return v.value
}

func (v *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) Set(val *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource(val *ComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource {
	return &NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseModelPageComEpamReportportalBaseReportingTestItemResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
