/*
ReportPortal

ReportPortal API documentation

API version: develop-531
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS{}

// ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS struct for ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS
type ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS struct {
	Id                   *int64                                                                `json:"id,omitempty"`
	Name                 *string                                                               `json:"name,omitempty"`
	Description          *string                                                               `json:"description,omitempty"`
	ExecutionStatistic   *ComEpamReportportalBaseCoreTmsDtoTmsTestPlanExecutionStatisticRS     `json:"executionStatistic,omitempty"`
	Attributes           []ComEpamReportportalBaseCoreTmsDtoTmsTestPlanAttributeRS             `json:"attributes,omitempty"`
	DuplicationStatistic *ComEpamReportportalBaseCoreTmsDtoBatchBatchTestCaseOperationResultRS `json:"duplicationStatistic,omitempty"`
}

// NewComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS instantiates a new ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS() *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS {
	this := ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS{}
	return &this
}

// NewComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRSWithDefaults instantiates a new ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRSWithDefaults() *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS {
	this := ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) SetDescription(v string) {
	o.Description = &v
}

// GetExecutionStatistic returns the ExecutionStatistic field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetExecutionStatistic() ComEpamReportportalBaseCoreTmsDtoTmsTestPlanExecutionStatisticRS {
	if o == nil || IsNil(o.ExecutionStatistic) {
		var ret ComEpamReportportalBaseCoreTmsDtoTmsTestPlanExecutionStatisticRS
		return ret
	}
	return *o.ExecutionStatistic
}

// GetExecutionStatisticOk returns a tuple with the ExecutionStatistic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetExecutionStatisticOk() (*ComEpamReportportalBaseCoreTmsDtoTmsTestPlanExecutionStatisticRS, bool) {
	if o == nil || IsNil(o.ExecutionStatistic) {
		return nil, false
	}
	return o.ExecutionStatistic, true
}

// HasExecutionStatistic returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) HasExecutionStatistic() bool {
	if o != nil && !IsNil(o.ExecutionStatistic) {
		return true
	}

	return false
}

// SetExecutionStatistic gets a reference to the given ComEpamReportportalBaseCoreTmsDtoTmsTestPlanExecutionStatisticRS and assigns it to the ExecutionStatistic field.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) SetExecutionStatistic(v ComEpamReportportalBaseCoreTmsDtoTmsTestPlanExecutionStatisticRS) {
	o.ExecutionStatistic = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetAttributes() []ComEpamReportportalBaseCoreTmsDtoTmsTestPlanAttributeRS {
	if o == nil || IsNil(o.Attributes) {
		var ret []ComEpamReportportalBaseCoreTmsDtoTmsTestPlanAttributeRS
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetAttributesOk() ([]ComEpamReportportalBaseCoreTmsDtoTmsTestPlanAttributeRS, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []ComEpamReportportalBaseCoreTmsDtoTmsTestPlanAttributeRS and assigns it to the Attributes field.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) SetAttributes(v []ComEpamReportportalBaseCoreTmsDtoTmsTestPlanAttributeRS) {
	o.Attributes = v
}

// GetDuplicationStatistic returns the DuplicationStatistic field value if set, zero value otherwise.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetDuplicationStatistic() ComEpamReportportalBaseCoreTmsDtoBatchBatchTestCaseOperationResultRS {
	if o == nil || IsNil(o.DuplicationStatistic) {
		var ret ComEpamReportportalBaseCoreTmsDtoBatchBatchTestCaseOperationResultRS
		return ret
	}
	return *o.DuplicationStatistic
}

// GetDuplicationStatisticOk returns a tuple with the DuplicationStatistic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) GetDuplicationStatisticOk() (*ComEpamReportportalBaseCoreTmsDtoBatchBatchTestCaseOperationResultRS, bool) {
	if o == nil || IsNil(o.DuplicationStatistic) {
		return nil, false
	}
	return o.DuplicationStatistic, true
}

// HasDuplicationStatistic returns a boolean if a field has been set.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) HasDuplicationStatistic() bool {
	if o != nil && !IsNil(o.DuplicationStatistic) {
		return true
	}

	return false
}

// SetDuplicationStatistic gets a reference to the given ComEpamReportportalBaseCoreTmsDtoBatchBatchTestCaseOperationResultRS and assigns it to the DuplicationStatistic field.
func (o *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) SetDuplicationStatistic(v ComEpamReportportalBaseCoreTmsDtoBatchBatchTestCaseOperationResultRS) {
	o.DuplicationStatistic = &v
}

func (o ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ExecutionStatistic) {
		toSerialize["executionStatistic"] = o.ExecutionStatistic
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.DuplicationStatistic) {
		toSerialize["duplicationStatistic"] = o.DuplicationStatistic
	}
	return toSerialize, nil
}

type NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS struct {
	value *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS
	isSet bool
}

func (v NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) Get() *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS {
	return v.value
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) Set(val *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) {
	v.value = val
	v.isSet = true
}

func (v NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) IsSet() bool {
	return v.isSet
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS(val *ComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) *NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS {
	return &NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS{value: val, isSet: true}
}

func (v NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComEpamReportportalBaseCoreTmsDtoDuplicateTmsTestPlanRS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
