/*
ReportPortal

ReportPortal API documentation

API version: 5.14.4
Contact: support@reportportal.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SaveAnalyticsSettings1401Response - struct for SaveAnalyticsSettings1401Response
type SaveAnalyticsSettings1401Response struct {
	ErrorRS *ErrorRS
	String  *string
}

// ErrorRSAsSaveAnalyticsSettings1401Response is a convenience function that returns ErrorRS wrapped in SaveAnalyticsSettings1401Response
func ErrorRSAsSaveAnalyticsSettings1401Response(v *ErrorRS) SaveAnalyticsSettings1401Response {
	return SaveAnalyticsSettings1401Response{
		ErrorRS: v,
	}
}

// stringAsSaveAnalyticsSettings1401Response is a convenience function that returns string wrapped in SaveAnalyticsSettings1401Response
func StringAsSaveAnalyticsSettings1401Response(v *string) SaveAnalyticsSettings1401Response {
	return SaveAnalyticsSettings1401Response{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *SaveAnalyticsSettings1401Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ErrorRS
	err = json.Unmarshal(data, &dst.ErrorRS)
	if err == nil {
		jsonErrorRS, _ := json.Marshal(dst.ErrorRS)
		if string(jsonErrorRS) == "{}" { // empty struct
			dst.ErrorRS = nil
		} else {
			match++
		}
	} else {
		dst.ErrorRS = nil
	}

	// try to unmarshal data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ErrorRS = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SaveAnalyticsSettings1401Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SaveAnalyticsSettings1401Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SaveAnalyticsSettings1401Response) MarshalJSON() ([]byte, error) {
	if src.ErrorRS != nil {
		return json.Marshal(&src.ErrorRS)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SaveAnalyticsSettings1401Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ErrorRS != nil {
		return obj.ErrorRS
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SaveAnalyticsSettings1401Response) GetActualInstanceValue() interface{} {
	if obj.ErrorRS != nil {
		return *obj.ErrorRS
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableSaveAnalyticsSettings1401Response struct {
	value *SaveAnalyticsSettings1401Response
	isSet bool
}

func (v NullableSaveAnalyticsSettings1401Response) Get() *SaveAnalyticsSettings1401Response {
	return v.value
}

func (v *NullableSaveAnalyticsSettings1401Response) Set(val *SaveAnalyticsSettings1401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSaveAnalyticsSettings1401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSaveAnalyticsSettings1401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSaveAnalyticsSettings1401Response(val *SaveAnalyticsSettings1401Response) *NullableSaveAnalyticsSettings1401Response {
	return &NullableSaveAnalyticsSettings1401Response{value: val, isSet: true}
}

func (v NullableSaveAnalyticsSettings1401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSaveAnalyticsSettings1401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
