name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2' # The Go version to download (if necessary) and use.
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v2.1.6
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: false
      # Run build of the application
      - name: Run build
        run: task build

      # Run testing on the code
      - name: Run testing
        run: task test
